# Generated by Django 5.1.7 on 2025-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.AutoField(db_column='term_id', primary_key=True, serialize=False)),
                ('term_ru', models.CharField(max_length=255)),
                ('term_en', models.CharField(max_length=255)),
                ('term_definition', models.TextField()),
            ],
        ),
    ]
